---
name: Release binary

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  binary-release:
    name: binary release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: make build-all

      - name: Generate checksums
        run: |
          cd _output
          sha256sum * > SHA256SUMS

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            _output/*
          generate_release_notes: true
