---
name: Release binary

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:

  binary-release:
    name: binary release
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v2

      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: build & test
        run: |
          make dependencies
          make build-all

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            _output/*
