---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "awa.fullname" . }}
  namespace: {{ include "awa.namespace" . }}
spec:
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
  selector:
    app: alertmanager-webhook-adapter
  sessionAffinity: None
